name: "detect-env-file-changes"
description: "Check for changes in the files with environment variables."
author: "Jovan Blazek"
icon: "message-circle"
color: "blue"
inputs:
  repo-token:
    description: "The GITHUB_TOKEN secret"
    required: false
    default: '${{ github.token }}'
  source-branch:
    description: "Source branch"
    required: false
    default: '${{ github.event.pull_request.head.ref }}'
  target-branch:
    description: "Target branch"
    required: false
    default: '${{ github.event.pull_request.base.ref }}'
  # files:
  #   description: "Files to check for changes. Use glob pattern. e.g. '**.env.example'"
  #   required: true

runs:
  using: 'node16'
  main: 'dist/index.js'