name: 'Detect env file changes'
description: 'Check for changes in the files with environment variables'
author: 'Jovan Blazek'
branding:
  icon: 'git-pull-request'
  color: 'blue'
inputs:
  target-branch:
    description: 'Target branch to compare against'
    required: false
    default: '${{ github.event.pull_request.base.ref }}'
  files:
    description: 'Files to check for changes. Check README for details on format'
    required: false
    default: '["**.env-example", "**.env-test-example"]'
outputs:
  env-changes-detected:
    description: 'Boolean value indicating if specified files have been changed'
  env-changes-raw:
    description: 'Raw output of changes'
  env-changes-md:
    description: 'Markdown output of changes'

runs:
  using: 'node16'
  main: 'dist/index.js'
